"""Research gallery: a plain-language question with an inspectable experiment."""
def experiment(id, name, title, simple, detail, features, gate, *, defaults=None, analytic=False):
    return dict(id=id,name=name,title=title,eyebrow='RESEARCH / '+name.upper(),simple=simple,detail=detail,
                features=features,defaults=defaults or {},next_gate=gate,section='research',
                data_kind='analytic' if analytic else 'native',
                question=simple)

PAGES = [
    experiment('samplers','Sampler engine','Choose the possibilities. Then add heat.',
        'Watch an actual native token distribution pass through each sampler. Move from what the model prefers to what the program can select.',
        'Six full-vocabulary runs compare operator order; three more combine sampling with GBNF or strict JSON. Raw logprobs precede every mask. Stage support and entropy come from the native selector, not the displayed top 20. This reference path uses CPU selection and target-only decoding.',
        ['native sampler','full vocabulary','GBNF','logprobs'],
        'Move this exact selector to the GPU; compare identical tensors, transfer bytes, latency and selected distributions before changing speculative verification.',
        defaults=dict(state='Name one useful workshop tool. Answer with one word.')),
    experiment('sampler-sandbox','Sampler sandbox','The order is the algorithm.',
        'Turn the dials on a tiny, completely visible distribution. See which ideas reshape weights and which remove choices.',
        'This finite synthetic row makes every number inspectable. The three priority recipes match the documented operators. DRY-like sequence penalties, entropy-driven temperature and surprise feedback are labeled teaching models, not claimed native DRY/Mirostat implementations.',
        ['analytic sandbox','operator ordering','feedback'],
        'Port one additional operator at a time, define history and rollback semantics, and test its numerical reference before advertising it.',analytic=True),
    experiment('tictactoe','Tic-tac-toe','Legal is easy. Winning is harder.',
        'A model plays X. A perfect small solver plays O. At every turn, the grammar permits only empty squares.',
        'The model supplies a distribution over legal actions. Exhaustive minimax supplies a separate outcome oracle. Their disagreement measures decision regret; grammar prevents illegal moves but does not confer strategy.',
        ['closed loop','state grammar','exact oracle'],
        'Compare legal-only sampling, oracle shielding and learned value estimates across every reachable state, with held-out positions and a fixed model-call budget.'),
    experiment('chess','Chess microscope','A valid move can still miss mate.',
        'Inspect a tiny chess position where code can prove mate in one. Compare that proof with the model’s preferences.',
        'python-chess validates the complete legal move set. The scorer measures a disclosed six-move shortlist containing a mating move and alternatives. The final grammar covers the entire legal set. Checkmate is checked by code; no chess-engine strength is claimed.',
        ['legal moves','GBNF','counterexample'],
        'Use tablebase-labelled endgames, legal full-set path scoring and deeper search. Compare quality per token, not merely legal-move rate.'),
    experiment('poker','Hidden information','The most likely answer is not the best bet.',
        'Three cards, two actions, one visible payoff calculation. Compare a model preference with a decision under an explicit opponent policy.',
        'A toy one-card betting game reveals the difference between an answer distribution and expected utility. The opponent policy and hidden-card prior are supplied by code. Values are exact for that policy, not equilibrium play or calibrated beliefs.',
        ['partial observation','expected utility','GBNF'],
        'Estimate opponent models on separate data, compute exploitability, and compare information-set policies instead of interpreting token probabilities as game beliefs.'),
    experiment('thermal','Cooling loop','Keep the engine in its lane.',
        'A simulated machine heats up. The model chooses a fan setting while a hard rule blocks unsafe commands.',
        'The discrete thermal plant has known dynamics and a changing load. A one-step safety shield removes commands whose modeled next temperature exceeds the limit. The model’s preference vector is an observation, not a stability proof. There is no physical hardware control.',
        ['feedback','safety filter','moving state'],
        'Add bounded disturbance, sensor delay, hysteresis and robust invariant-set analysis. Evaluate violations and oscillation against an ordinary controller.'),
    experiment('scheduler','Job scheduler','Spend a token where it buys the most.',
        'A tiny work queue has dependencies and deadlines. The model ranks jobs; code prevents impossible execution.',
        'Each step rebuilds a grammar from jobs whose dependencies are complete. A deterministic simulation accounts for durations and lateness. Compare semantic preference with an earliest-deadline baseline. These are toy jobs, not OS commands.',
        ['dependency graph','state injection','utility'],
        'Measure dispatch regret and real wall time on an external benchmark. HTTP concurrency is not native GPU batching.'),
    experiment('context','Context surgery','Rewrite the state. Watch the answer move.',
        'An old note says the door is open. A new sensor says it is closed. Compare appending a correction, replacing history, and injecting only current state.',
        'Every condition is an ordinary request with explicit retained text. The service may reuse an identical token prefix and recompute the changed suffix. This is prompt rewriting and re-prefill, not direct KV tensor editing. The two repeated current-state requests expose timing and cache fields when provided by the server.',
        ['state intervention','context replay','prefill'],
        'Instrument exact reused-token counts, changed-prefix boundaries and native recurrent state. Arbitrary KV rewriting needs a separate verified engine design.'),
    experiment('observer','Semantic observer','Meaning becomes a measurement vector.',
        'Read three incident reports through the same small set of questions. Watch a controller observe meaning without asking for rewritten prose.',
        'The vector contains separate yes/no semantic probes: fault, missing evidence, and completion. A fixed rule maps that vector to an action. Shared evidence means the components are not independent; multiplying them would not give workflow reliability.',
        ['compressed state','observer','logprobs'],
        'Test observability against latent process states, measure drift and prompt sensitivity, then compare with lexical and supervised baselines.'),
    experiment('calibration','Calibration bench','A sharp answer can still be wrong.',
        'Compare model probabilities with answers we can check. Slide the abstention threshold and see how coverage changes.',
        'A small disclosed set of deterministic propositions illustrates Brier score, reliability bins and selective accuracy. It is a teaching set, not a held-out calibration benchmark. A label-swapped repeat exposes prompt sensitivity.',
        ['Brier score','abstention','label sensitivity'],
        'Separate calibration and test sets, add enough samples for uncertainty intervals, and report proper scores by task and model rather than claiming universal confidence.'),
    experiment('information','Active inspection','Which question is worth asking next?',
        'A machine has three possible faults. Choose a test that reduces uncertainty, then ask the model to use the resulting evidence.',
        'The hidden-state prior and test likelihoods are explicit synthetic numbers. Code computes expected information gain and Bayes updates. The model receives the observation and proposes the next action under a grammar. Its answer weights are not substituted for sensor likelihoods.',
        ['information gain','Bayes update','measurement cost'],
        'Learn and validate observation likelihoods, include action-dependent sensing costs, and compare a belief-state controller with reactive rules.'),
    experiment('search','Program search','Let meaning guide a very small search.',
        'Enumerate tiny drawing programs. Code checks geometry, the model measures an instruction, and search trades fit against cost.',
        'Six bounded scene candidates preserve their program text. Explicit constraints reject overlaps; yes/no probes score a relation. A disclosed utility trades semantic weight against program cost. Human viewing remains separate from the text-only scorer.',
        ['bounded search','semantic objective','hard checks'],
        'Use real rendered judgments, multiple seeds and an independent evaluator. Measure quality per call against unconstrained generation and a code-only baseline.'),
    experiment('frontier','Cost frontier','Where does the next millisecond go?',
        'Separate model work, score transfer, selection and control. Move assumptions to see which optimization could matter.',
        'Native sampler receipts supply selection timings and full-row sizes. Bandwidth, power and tariff dials are user assumptions. The chart is an engineering lower-bound calculation, not hardware telemetry or a measured roofline.',
        ['cost model','bandwidth','quality per call'],
        'Collect GPU counters and isolated copy/kernel timings. Preserve same-tensor correctness while testing compact gather, prefix sharing and batched scoring.',analytic=True),
    experiment('research-map','Possibility tree','A hammer, a hundred possible nails.',
        'Explore the branches from semantic measurement to control, search, and unusual applications. Every branch has an experiment that could fail.',
        'The map distinguishes implemented native controls, recorded applications, analytical simulations and open research. It connects token-level selection to observers, constrained graph solvers, games and optimization without claiming new computational expressivity.',
        ['research agenda','falsifiable gates','manual controls'],
        'Pick one branch, freeze a baseline, define a failure metric, and measure before optimizing.',analytic=True),
]
