"""Larger research proposals, linked to their deliberately bounded first demos."""

APPLIED_IDS={'Musical tension':'music','Proof tactic budget':'proof','Compiler treasure hunt':'compiler',
             'Circuit sketches':'divider','Database choreography':'transaction','Belief camouflage':'camouflage',
             'Adversarial grammar':'adversary','Token economy':'budget'}

def idea(name,path,hypothesis,intervention,baseline,measure,failure):
    return dict(name=name,path=path,page=APPLIED_IDS[name],status='Working bounded demo; larger research gate open',
                gate='Inspect the checked toy and its native receipts. The larger experiment below still needs its own verifier, benchmark and fixed budget.',
                protocol=dict(Hypothesis=hypothesis,Intervention=intervention,Baseline=baseline,
                              Measurement=measure,Failure=failure))

IDEAS = [
    idea('Musical tension','Meter and key → legal notes → controlled surprise',
         'Grammar can keep a melody playable while a sampler explores locally unusual continuations.',
         'Inject bar position and harmonic state each beat. Compare cold Min-P then heat with XTC. Keep the same legal-note set.',
         'A Markov melody generator and random legal notes under the same timing rules.',
         'Blind listening preference, repetition, rule violations and native milliseconds per bar. Raw token surprise stays separate from musical novelty.',
         'Tokenization makes note probabilities incomparable, or higher surprise only creates worse music.'),
    idea('Proof tactic budget','Proof state → type-valid tactics → checked progress',
         'A weak proposal distribution may still help a strong proof checker search efficiently.',
         'Generate only registered tactic names; let a sandboxed prover reject invalid applications. Replace stale goals with the current proof state after each accepted step.',
         'Uniform tactic search, fixed heuristics and unconstrained generation at the same checker-call budget.',
         'Solved held-out theorems, verifier calls, time and rollback count. A high path score is not a proof.',
         'The grammar covers syntax but excludes a necessary tactic, or scoring costs more than search saves.'),
    idea('Compiler treasure hunt','Typed rewrite → equivalence check → measured speed',
         'Semantic guidance might find rare useful rewrites in a large but checkable neighborhood.',
         'GBNF admits a small rewrite language. Compare Min-P exploration and XTC candidates; verify equivalence before benchmarking.',
         'Compiler defaults, enumerative peephole search and random legal rewrites.',
         'Held-out runtime, compile time, verifier failures and quality per generated token. Control warmup and measurement noise.',
         'A benchmark artifact looks like a speedup, or a legal rewrite breaks semantics.'),
    idea('Circuit sketches','Topology grammar → simulator → robust design search',
         'Language priors could prioritize useful circuit motifs even when physics is owned by code.',
         'Enumerate safe simulated component choices. Inject operating points and tolerance results; score whole candidate paths before expensive simulations.',
         'Random legal circuits, Bayesian optimization and domain heuristics with identical simulator budgets.',
         'Feasibility, worst-case performance across tolerances, simulation cost and diversity of successful motifs.',
         'The language model prefers familiar-looking circuits that systematically fail physics. No physical actuation is part of this proposal.'),
    idea('Database choreography','Snapshot → permitted transaction → invariant check',
         'State-derived grammars may prevent a workflow from issuing commands that are impossible in its current transaction state.',
         'Expose a small transaction DSL, not unrestricted SQL. Replace state after each committed transaction; adversarially inject a stale snapshot.',
         'A deterministic workflow and optimistic concurrency with ordinary retries.',
         'Invariant violations, stale-state refusals, retries and completion cost under injected conflicts.',
         'The grammar encodes an old world. Database concurrency control still owns correctness.'),
    idea('Belief camouflage','Same world → different wording → invariant controller',
         'A useful semantic observer should preserve action decisions under irrelevant paraphrase.',
         'Keep hidden simulator state fixed while varying narrative, label order and distractors. Use probe vectors as features; measure drift before changing the controller.',
         'Direct structured state, lexical rules and a supervised observer.',
         'Vector drift, action invariance, proper scoring rules and closed-loop regret on held-out paraphrases.',
         'The controller follows wording rather than state; correlated probes give the illusion of redundant evidence.'),
    idea('Adversarial grammar','Allowed does not mean wise → find the weakest legal action',
         'Grammar can make an application syntactically robust while concentrating every error on a small set of legal but bad actions.',
         'Search state descriptions that maximize oracle regret inside a fixed legal set. Replay the exact winning counterexample across sampler orders.',
         'Random perturbations, a deterministic policy and unconstrained generation at equal query counts.',
         'Legal rate, strategy regret, constraint exhaustion, recovery time and failure diversity.',
         'Only easy syntax errors were measured; the evaluation never tested meaningful state mistakes.'),
    idea('Token economy','Look ahead, ask, or act → allocate a finite inference budget',
         'A controller could spend extra scoring calls only where their expected decision benefit exceeds their measured cost.',
         'Use an explicit abstain/inspect/act policy; price prefill, scoring, verification and context rewrite separately. Sweep budgets instead of picking one favorable point.',
         'Always act, always inspect and fixed-depth search with the same end-to-end budget.',
         'Outcome quality versus wall time, energy assumptions, verified tokens and discarded drafts. A decision frontier needs real outcomes.',
         'Confidence is mistaken for calibrated value of information, or observer overhead consumes the saved latency.'),
]
